# Generated by Django 6.0 on 2025-12-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_subjects_course_subject'),
        ('enrollments', '0002_auto_20251213_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='courses.course'),
        ),
    ]
